<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Drop the FK constraint on produk_saya.account_id → account_shop_tiktok
 * so the table can store products from ANY platform (TikTok, Shopee, etc.).
 *
 * The account_id now references:
 *   - account_shop_tiktok.id  when platform = 'TIKTOK' / 'TOKOPEDIA'
 *   - account_shop_shopee.id  when platform = 'SHOPEE'
 *
 * Platform disambiguation is handled via the `platform` and `channel_id` columns.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('produk_saya', function (Blueprint $table) {
            // Drop the FK constraint (name generated by Laravel convention)
            $table->dropForeign(['account_id']);
        });
    }

    public function down(): void
    {
        Schema::table('produk_saya', function (Blueprint $table) {
            $table->foreign('account_id')
                ->references('id')->on('account_shop_tiktok')
                ->cascadeOnDelete();
        });
    }
};
